# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Аферисты Avito
email: admin@aferisty-avito.tk
description: Черный список аферистов Avito
baseurl: "" 
url: "http://johnbel.github.io" 

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]


twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
