title: Новости Android
email: admin@novosti-android.ru
description: Новости мира Android
baseurl: "/" 
url: "http://johnbel.github.io/" 
paginate: 25
paginate_path: "/blog/page:num/"

permalink: /:year/:month/:day/:title.html

plugins: [jekyll-paginate]

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  #startings: [html, head, body]

  gems:
  - jekyll-feed



# Build settings
markdown: kramdown
